"""add messages and inbox fields

Revision ID: 02d5dff79d4f
Revises: 1c3440471251
Create Date: 2026-08-08 22:17:26.188440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02d5dff79d4f'
down_revision: Union[str, Sequence[str], None] = '1c3440471251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('customer_phone', sa.String(length=30), nullable=False))
    op.add_column('conversations', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('last_message_text', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('unread_count', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('is_open', sa.Boolean(), nullable=False))
    op.add_column('conversations', sa.Column('is_starred', sa.Boolean(), nullable=False))
    op.add_column('conversations', sa.Column('assigned_user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_conversations_contact_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.create_index(op.f('ix_conversations_assigned_user_id'), 'conversations', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_phone'), 'conversations', ['customer_phone'], unique=False)
    op.drop_constraint(op.f('conversations_contact_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('conversations', 'contact_id')
    op.drop_column('conversations', 'status')
    op.drop_column('conversations', 'last_message_preview')
    op.add_column('messages', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('media_url', sa.Text(), nullable=True))
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'body')
    op.drop_column('messages', 'delivered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('messages', 'media_url')
    op.drop_column('messages', 'text')
    op.add_column('conversations', sa.Column('last_message_preview', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_contact_id_fkey'), 'conversations', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_customer_phone'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_contact_id'), 'conversations', ['contact_id'], unique=False)
    op.drop_column('conversations', 'assigned_user_id')
    op.drop_column('conversations', 'is_starred')
    op.drop_column('conversations', 'is_open')
    op.drop_column('conversations', 'unread_count')
    op.drop_column('conversations', 'last_message_text')
    op.drop_column('conversations', 'customer_name')
    op.drop_column('conversations', 'customer_phone')
    # ### end Alembic commands ###
