"""add customers table

Revision ID: 2db008e57d2f
Revises: 02d5dff79d4f
Create Date: 2026-08-08 22:39:01.804868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db008e57d2f'
down_revision: Union[str, Sequence[str], None] = '02d5dff79d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_connection_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_connection_id'], ['whatsapp_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customers_provider_customer_id'), 'customers', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_customers_whatsapp_connection_id'), 'customers', ['whatsapp_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_whatsapp_connection_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_provider_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
