"""add meta oauth states

Revision ID: 677a6b7da162
Revises: 68620d930c50
Create Date: 2026-08-07 23:18:39.431619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677a6b7da162'
down_revision: Union[str, Sequence[str], None] = '68620d930c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_oauth_states',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_oauth_states_organization_id'), 'meta_oauth_states', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meta_oauth_states_state'), 'meta_oauth_states', ['state'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_oauth_states_state'), table_name='meta_oauth_states')
    op.drop_index(op.f('ix_meta_oauth_states_organization_id'), table_name='meta_oauth_states')
    op.drop_table('meta_oauth_states')
    # ### end Alembic commands ###
