"""add meta webhook events

Revision ID: 86e4529d673d
Revises: c2d1580b96ee
Create Date: 2026-08-09 00:11:13.984312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e4529d673d'
down_revision: Union[str, Sequence[str], None] = 'c2d1580b96ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_webhook_events',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('waba_id', sa.String(length=100), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_webhook_events_event_hash'), 'meta_webhook_events', ['event_hash'], unique=True)
    op.create_index(op.f('ix_meta_webhook_events_organization_id'), 'meta_webhook_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meta_webhook_events_waba_id'), 'meta_webhook_events', ['waba_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_webhook_events_waba_id'), table_name='meta_webhook_events')
    op.drop_index(op.f('ix_meta_webhook_events_organization_id'), table_name='meta_webhook_events')
    op.drop_index(op.f('ix_meta_webhook_events_event_hash'), table_name='meta_webhook_events')
    op.drop_table('meta_webhook_events')
    # ### end Alembic commands ###
