"""add whatsapp connections

Revision ID: 9bd08e208e06
Revises: 393039d840a0
Create Date: 2026-08-07 16:11:59.050080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd08e208e06'
down_revision: Union[str, Sequence[str], None] = '393039d840a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_connections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('waba_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number_id', sa.String(length=100), nullable=False),
    sa.Column('display_phone_number', sa.String(length=50), nullable=True),
    sa.Column('verified_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_connections_organization_id'), 'whatsapp_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_connections_phone_number_id'), 'whatsapp_connections', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_connections_waba_id'), 'whatsapp_connections', ['waba_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_connections_waba_id'), table_name='whatsapp_connections')
    op.drop_index(op.f('ix_whatsapp_connections_phone_number_id'), table_name='whatsapp_connections')
    op.drop_index(op.f('ix_whatsapp_connections_organization_id'), table_name='whatsapp_connections')
    op.drop_table('whatsapp_connections')
    # ### end Alembic commands ###
