"""add whatsapp messages and conversation fields

Revision ID: c2d1580b96ee
Revises: 2db008e57d2f
Create Date: 2026-08-08 23:38:08.030902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2d1580b96ee'
down_revision: Union[str, Sequence[str], None] = '2db008e57d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_attachments',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('attachment_type', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('provider_media_id', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_attachment_type'), 'message_attachments', ['attachment_type'], unique=False)
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_provider_media_id'), 'message_attachments', ['provider_media_id'], unique=False)
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone_number'), table_name='contacts')
    op.drop_table('contacts')
    op.add_column('conversations', sa.Column('customer_phone_number', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_conversations_assigned_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_phone'), table_name='conversations')
    op.create_index(op.f('ix_conversations_customer_phone_number'), 'conversations', ['customer_phone_number'], unique=False)
    op.drop_constraint(op.f('conversations_assigned_user_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'unread_count')
    op.drop_column('conversations', 'assigned_user_id')
    op.drop_column('conversations', 'customer_phone')
    op.drop_column('conversations', 'is_open')
    op.drop_column('conversations', 'customer_name')
    op.drop_column('conversations', 'is_starred')
    op.drop_column('conversations', 'last_message_text')
    op.add_column('messages', sa.Column('sender_phone_number', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('whatsapp_timestamp', sa.String(length=50), nullable=False))
    op.alter_column('messages', 'whatsapp_message_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('messages', 'media_url')
    op.drop_column('messages', 'sent_at')
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('messages', 'whatsapp_message_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('messages', 'whatsapp_timestamp')
    op.drop_column('messages', 'sender_phone_number')
    op.add_column('conversations', sa.Column('last_message_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('is_starred', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('customer_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('assigned_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('unread_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('conversations_assigned_user_id_fkey'), 'conversations', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_conversations_customer_phone_number'), table_name='conversations')
    op.create_index(op.f('ix_conversations_customer_phone'), 'conversations', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_conversations_assigned_user_id'), 'conversations', ['assigned_user_id'], unique=False)
    op.drop_column('conversations', 'customer_phone_number')
    op.create_table('contacts',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('contacts_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('contacts_pkey'))
    )
    op.create_index(op.f('ix_contacts_phone_number'), 'contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_message_attachments_provider_media_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_attachment_type'), table_name='message_attachments')
    op.drop_table('message_attachments')
    # ### end Alembic commands ###
